nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173'] # Allow your frontend origin
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-CSRF-Token']
        expose_headers: ['Link']
        max_age: 3600
        hosts: []
        origin_regex: false
        allow_credentials: true

    paths:
        '^/api/': # Apply these rules to all /api/* routes
            allow_origin: ['http://localhost:5173']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization', 'X-CSRF-Token']
            expose_headers: []
            max_age: 3600
            allow_credentials: true
